# build image
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

COPY . .
RUN dotnet restore WebSubClient/WebSubClient.csproj

COPY . .
RUN dotnet publish WebSubClient/WebSubClient.csproj --output /out/ --configuration Release

# runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build /out .
ENV ASPNETCORE_ENVIRONMENT=Docker
ENTRYPOINT [ "dotnet", "WebSubClient.dll" ]

EXPOSE 80
